repos:
  - repo: local
    hooks:
     - id: flake8
       name: flake8
       entry: flake8
       language: system
     - id: isort
       name: isort
       entry: isort .
       language: system
     - id: mypy
       name: mypy
       entry: mypy . --ignore-missing-imports
       pass_filenames: false
       language: system
       types: [python]
