version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: dmitry_tok
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: djangogramm
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - mynetwork
  web:
    image: 258647/djangogramm
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      mynetwork:
        aliases:
          - application

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge