[tool.flake8]
exclude = [
    "venv",
    "migrations",
    ".pre-commit-config.yaml",
    "pyproject.toml",
    "Makefile",
    "requirements.txt",
    "Dockerfile",
    "docker-compose.yml",
    ".gitignore",
    "example_env_file",
    ".coveragerc",
    "README.md"
]
max-line-length = 120

[tool.mypy]
exclude = ["djangogramm_app/migrations/*"]
warn_unused_configs = true
ignore_missing_imports = true

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
