[tool.flake8]
exclude = ['venv']
max-line-length = 120
ignore = ["E203", "E266", "E501", "W503", "F403", "F401", "E999", "E501"]

[tool.mypy]
warn_unused_configs = true
ignore_missing_imports = true

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
