# Generated by Django 4.1.7 on 2023-03-06 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_avatar'),
        ('djangogramm_app', '0002_alter_avatar_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
