# Generated by Django 4.1.7 on 2023-06-04 08:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm_app', '0004_alter_pictures_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
