# Generated by Django 4.1.7 on 2023-06-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm_app', '0005_alter_pictures_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='picture',
            field=models.ImageField(upload_to='pictures'),
        ),
    ]
