# Generated by Django 4.1.7 on 2023-06-07 18:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm_app', '0007_alter_pictures_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
