# Generated by Django 4.1.7 on 2023-06-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm_app', '0008_pictures_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pictures',
            field=models.ManyToManyField(
                blank=True, null=True, related_name='post_picture', to='djangogramm_app.pictures'),
        ),
    ]
