# Generated by Django 4.1.7 on 2023-06-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm_app', '0010_alter_pictures_avatar_alter_pictures_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pictures',
            field=models.ManyToManyField(blank=True, related_name='post_picture', to='djangogramm_app.pictures'),
        ),
    ]
